name = "ToolipsSVG"
uuid = "8ae86ec9-919d-4ece-9a6d-09b7d28dae11"
authors = ["emmac <emmettgb@gmail.com>"]
version = "0.2.0"

[deps]
ToolipsServables = "bf3a9e68-ca66-4981-8178-9d71c4f8abaa"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.0"
ToolipsServables = "0.1.2"
